Garcia, Alvin Reagan D.

2ECEB

Advanced Programming assignment 2

09/01/25

1. NORMALIZATION PROBLEM

In [16]:
import numpy as np
x = np.random.random ((5,5)) 
mean = x.mean ()
std = x.std ()

Normalize_x = (x - mean) / std

print(Normalize_x)
np.save('X_Normalized.npy', Normalize_x)

[[-0.66662792 -0.61656824 -1.02271542  0.61015354 -0.7605974 ]
 [-1.08606475 -0.35109952 -1.06804178  0.19727998  0.92976748]
 [-1.28510139 -1.1677901  -0.38462543 -0.57346085  1.76787347]
 [ 1.41986275  1.09392613  1.81130437 -0.18356433  1.14245656]
 [-0.09159362  0.25125712 -0.81468894  1.70625184 -0.85759354]]


2. DIVISIBLE BY 3 PROBLEM

In [38]:
import numpy as np
a = np.arange(1,101).reshape((10,10))
a2 = a **2
a3 = a2.copy()
a3[ a3 % 3 != 0 ] = 0

print(a3)
np.save ('div_by_3',a3)

[[   0    0    9    0    0   36    0    0   81    0]
 [   0  144    0    0  225    0    0  324    0    0]
 [ 441    0    0  576    0    0  729    0    0  900]
 [   0    0 1089    0    0 1296    0    0 1521    0]
 [   0 1764    0    0 2025    0    0 2304    0    0]
 [2601    0    0 2916    0    0 3249    0    0 3600]
 [   0    0 3969    0    0 4356    0    0 4761    0]
 [   0 5184    0    0 5625    0    0 6084    0    0]
 [6561    0    0 7056    0    0 7569    0    0 8100]
 [   0    0 8649    0    0 9216    0    0 9801    0]]
